### ISSUE TITLE
Qrcode tag not working

### ISSUE THREAD

**Issue by Danmanu44** [hamidrezahy/Blazor.QRCode#1]
I add the NuGet package and add the script tags in an index.html but showing  ReferenceError: QRCode is not defined
          at initQrCode (https://localhost:7234/_content/Blazor.QRCode/qrcode-init.js:16:5)

**Comment by Danmanu44** [comment]
I added qrcode.min.js library and it works

**Comment by hamidrezahy** [comment]
thanks for report.

I fixed and publish on nuget.
